name: cronjob

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: private-slack-workspace
          - environment: akerun
          - environment: karakuri-nims
    environment: ${{ matrix.environment }}
    env:
      ARXIV_QUERY: ${{ vars.ARXIV_QUERY }}
      SUMMARIZE_CONTENT: ${{ vars.SUMMARIZE_CONTENT }}
      SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
          cache: "pipenv"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev
      - name: Run script
        run: |
          pipenv run python src/main.py
