name: cronjob

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  post-to-slack:
    runs-on: ubuntu-latest

    env:
      ARXIV_QUERY: "ti:%22 Materials Informatics %22"
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
          cache: "pipenv"
      - run: echo $ARXIV_QUERY
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev
      - name: Run script
        run: |
          pipenv run python src/main.py
